# Generated by Django 4.1 on 2022-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebServer', '0002_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
